kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-ui
  labels:
    app: webapp-ui
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: webapp-ui
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp-ui
    spec:
      restartPolicy: Always
      containers:
      - name: webapp-ui
        image: gcr.io/concrete-crow-297015/webapp-ui:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "500Mi"
          limits:
            memory: "500Mi"
        ports:
        - containerPort: 4200
          name: http
      imagePullSecrets:
        - name: storecheckersecretlatest
