kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-two-db
  labels:
    app: frontend
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: service-two-db
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-two-db
    spec:
      restartPolicy: Always
      containers:
      - name: service-two-db
        image: mysql/mysql-server:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root123"
        - name: MYSQL_DATABASE
          value: "service-two"
        - name: MYSQL_USER
          value: "service-two"
        - name: MYSQL_PASSWORD
          value: "service-two"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.2"
            memory: "500Mi"
          limits:
            memory: "600Mi"
        ports:
        - containerPort: 3306
          name: http
